export interface BibleName {
  bcode: number;
  name: string;
  abbreviations: string[];
}

export const BIBLE_NAMES: BibleName[] = [
  { bcode: 1, name: '창세기', abbreviations: ['창', 'Gen'] },
  { bcode: 2, name: '출애굽기', abbreviations: ['출', 'Exo'] },
  { bcode: 3, name: '레위기', abbreviations: ['레', 'Lev'] },
  { bcode: 4, name: '민수기', abbreviations: ['민', 'Num'] },
  { bcode: 5, name: '신명기', abbreviations: ['신', 'Deu'] },
  { bcode: 6, name: '여호수아', abbreviations: ['수', 'Jos'] },
  { bcode: 7, name: '사사기', abbreviations: ['삿', 'Jdg'] },
  { bcode: 8, name: '룻기', abbreviations: ['룻', 'Rut'] },
  { bcode: 9, name: '사무엘상', abbreviations: ['삼상', '1Sa'] },
  { bcode: 10, name: '사무엘하', abbreviations: ['삼하', '2Sa'] },
  { bcode: 11, name: '열왕기상', abbreviations: ['왕상', '1Ki'] },
  { bcode: 12, name: '열왕기하', abbreviations: ['왕하', '2Ki'] },
  { bcode: 13, name: '역대상', abbreviations: ['대상', '1Ch'] },
  { bcode: 14, name: '역대하', abbreviations: ['대하', '2Ch'] },
  { bcode: 15, name: '에스라', abbreviations: ['스', 'Ezr'] },
  { bcode: 16, name: '느헤미야', abbreviations: ['느', 'Neh'] },
  { bcode: 17, name: '에스더', abbreviations: ['에', 'Est'] },
  { bcode: 18, name: '욥기', abbreviations: ['욥', 'Job'] },
  { bcode: 19, name: '시편', abbreviations: ['시', 'Psa'] },
  { bcode: 20, name: '잠언', abbreviations: ['잠', 'Pro'] },
  { bcode: 21, name: '전도서', abbreviations: ['전', 'Ecc'] },
  { bcode: 22, name: '아가', abbreviations: ['아', 'Sng'] },
  { bcode: 23, name: '이사야', abbreviations: ['사', 'Isa'] },
  { bcode: 24, name: '예레미야', abbreviations: ['렘', 'Jer'] },
  { bcode: 25, name: '예레미야애가', abbreviations: ['애', 'Lam'] },
  { bcode: 26, name: '에스겔', abbreviations: ['겔', 'Eze'] },
  { bcode: 27, name: '다니엘', abbreviations: ['단', 'Dan'] },
  { bcode: 28, name: '호세아', abbreviations: ['호', 'Hos'] },
  { bcode: 29, name: '요엘', abbreviations: ['욜', 'Joe'] },
  { bcode: 30, name: '아모스', abbreviations: ['암', 'Amo'] },
  { bcode: 31, name: '오바댜', abbreviations: ['옵', 'Oba'] },
  { bcode: 32, name: '요나', abbreviations: ['욘', 'Jon'] },
  { bcode: 33, name: '미가', abbreviations: ['미', 'Mic'] },
  { bcode: 34, name: '나훔', abbreviations: ['나', 'Nah'] },
  { bcode: 35, name: '하박국', abbreviations: ['합', 'Hab'] },
  { bcode: 36, name: '스바냐', abbreviations: ['습', 'Zep'] },
  { bcode: 37, name: '학개', abbreviations: ['학', 'Hag'] },
  { bcode: 38, name: '스가랴', abbreviations: ['슥', 'Zec'] },
  { bcode: 39, name: '말라기', abbreviations: ['말', 'Mal'] },
  { bcode: 40, name: '마태복음', abbreviations: ['마', 'Mat'] },
  { bcode: 41, name: '마가복음', abbreviations: ['막', 'Mar'] },
  { bcode: 42, name: '누가복음', abbreviations: ['눅', 'Luk'] },
  { bcode: 43, name: '요한복음', abbreviations: ['요', 'Jhn'] },
  { bcode: 44, name: '사도행전', abbreviations: ['행', 'Act'] },
  { bcode: 45, name: '로마서', abbreviations: ['롬', 'Rom'] },
  { bcode: 46, name: '고린도전서', abbreviations: ['고전', '1Co'] },
  { bcode: 47, name: '고린도후서', abbreviations: ['고후', '2Co'] },
  { bcode: 48, name: '갈라디아서', abbreviations: ['갈', 'Gal'] },
  { bcode: 49, name: '에베소서', abbreviations: ['엡', 'Eph'] },
  { bcode: 50, name: '빌립보서', abbreviations: ['빌', 'Php'] },
  { bcode: 51, name: '골로새서', abbreviations: ['골', 'Col'] },
  { bcode: 52, name: '데살로니가전서', abbreviations: ['살전', '1Th'] },
  { bcode: 53, name: '데살로니가후서', abbreviations: ['살후', '2Th'] },
  { bcode: 54, name: '디모데전서', abbreviations: ['딤전', '1Ti'] },
  { bcode: 55, name: '디모데후서', abbreviations: ['딤후', '2Ti'] },
  { bcode: 56, name: '디도서', abbreviations: ['딛', 'Tts'] },
  { bcode: 57, name: '빌레몬서', abbreviations: ['몬', 'Phm'] },
  { bcode: 58, name: '히브리서', abbreviations: ['히', 'Heb'] },
  { bcode: 59, name: '야고보서', abbreviations: ['약', 'Jas'] },
  { bcode: 60, name: '베드로전서', abbreviations: ['벧전', '1Pe'] },
  { bcode: 61, name: '베드로후서', abbreviations: ['벧후', '2Pe'] },
  { bcode: 62, name: '요한1서', abbreviations: ['요일', '1Jn'] },
  { bcode: 63, name: '요한2서', abbreviations: ['요이', '2Jn'] },
  { bcode: 64, name: '요한3서', abbreviations: ['요삼', '3Jn'] },
  { bcode: 65, name: '유다서', abbreviations: ['유', 'Jud'] },
  { bcode: 66, name: '요한계시록', abbreviations: ['계', 'Rev'] },
];
